version: '3.7'
services:
  app:
    container_name: app
    image: javiaz/flask:latest
    build: .
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    depends_on:
    - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=flask_db
networks:
  default:
    external:
      name: flask_net
